<?php

/**
 * @file
 * Enhanced control over the CSS ides of any Block.
 *
 * Block Class allows users to add ides to any block through the block's
 * configuration interface. This implementation is based on an alteration of
 * the Core block database table to leverage the Core Block API functions,
 * objects and structure.
 */

/**
 * Implements hook_permission().
 */
function naviteam_block_attributes_permission() {
  return array(
    'administer block ides' => array(
      'title' => t('Administer block ides'),
      'description' => t('Set CSS ides for blocks.'),
    ),
  );
}

/**
 * Implements theme_preprocess_block().
 *
 * Extend block's ides with any user defined ides.
 
function naviteam_block_attributes_preprocess_block(&$vars) {
  $block = $vars['block'];
  if (isset($block->naviteam_block_attributes) && $block->naviteam_block_attributes != '') {
    $vars['ides_array'] = array_merge($vars['ides_array'], explode(' ', $block->naviteam_block_attributes));
  }
}
*/
/**
 * Implements hook_preprocess_HOOK().
 *
 * Extend panel block's ides with any user defined ides.
 */
function naviteam_block_attributes_preprocess_panels_pane(&$vars) {
  if ($vars['pane']->type != 'block') {
    return;
  }
  // Infer the block's $module and $delta from the pane subtype.
  $block_parts = explode('-', $vars['pane']->subtype);
  // Load the block based on the block parts.
  $block = block_load($block_parts[0], $block_parts[1]);
  // Add a generic 'module type' pane class.
  $vars['ides_array'][] = drupal_html_class('pane-' . $block->module);
  // Add $naviteam_block_attributes to the $ides_array.
  if (isset($block->naviteam_block_attributes) && $block->naviteam_block_attributes != '') {
    $vars['ides_array'] = array_merge($vars['ides_array'], explode(' ', $block->naviteam_block_attributes));
  }
}

/**
 * Implements hook_form_alter().
 *
 * Alter block edit form to add configuration field.
 */
function naviteam_block_attributes_form_alter(&$form, &$form_state, $form_id) {
  if (user_access('administer block ides') && ($form_id == 'block_admin_configure' || $form_id == 'block_add_block_form')) {
    // Load statically cached block object used to display the form.
    $block = block_load($form['module']['#value'], $form['delta']['#value']);

    $form['settings']['naviteam_block_attributes'] = array(
      '#type' => 'textarea',
      '#title' => t('Custom attributes'),
      '#default_value' => isset($block->naviteam_block_attributes) ? $block->naviteam_block_attributes : '',
      '#description' => t('Example: style="color:red;font-size:14px" data-bg="background"'),
    );

    $form['#submit'][] = 'naviteam_block_attributes_form_submit';
  }
}

/**
 * Helper function: additional submit callback for block configuration pages.
 *
 * Save supplied CSS ides.
 */
function naviteam_block_attributes_form_submit($form, &$form_state) {
  if ($form_state['values']['form_id'] == 'block_admin_configure' || $form_state['values']['form_id'] == 'block_add_block_form') {
    // Only save if value has changed.
    if (isset($form_state['values']['naviteam_block_attributes']) && $form['settings']['naviteam_block_attributes']['#default_value'] != $form_state['values']['naviteam_block_attributes'] && user_access('administer blocks')) {
      db_update('block')
        ->fields(array('naviteam_block_attributes' => $form_state['values']['naviteam_block_attributes']))
        ->condition('module', $form_state['values']['module'])
        ->condition('delta', $form_state['values']['delta'])
        ->execute();
      // Flush all context module cache to use the updated naviteam_block_attributes.
      if (module_exists('context')) {
        cache_clear_all('context', 'cache', TRUE);
      }
    }
  }
}
